kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile-sc-premium
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - actimeo=30
  - nosharesock
parameters:
  skuName: Premium_LRS
