apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-pvc-standard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi
